blank_issues_enabled: false
contact_links:
  - name: Report Your Bug
    url: https://github.com/pieces-app/support/issues/new?template=bug.yml
    about: Submit your bug or issues here for the Pieces team to resolve!